runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /app
  script: main.app
  login: required
  auth_fail_action: redirect
  secure: always
  
- url: /.*
  script: main.app
  login: optional
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest